### ISSUE TITLE
404 error on all pages on a fresh install

### ISSUE THREAD

**Issue by vfiack** [nomad-nmr/nomad-front-end#3]
The front-end tries to get the dashboard, and select the first tab (0).
On a fresh install, the database is empty, and no instrument is defined yet.

A quick fix is to remove the call to `fetchStatusTable('0')` in `src/containers/Dashboard/Dashboard.js` first `useEffect(..)` call.
This can be reverted once at least once an instrument exists.

Not creating a PR because I'm not confident that this doesn't have a side-effect that you'd rather not have.
A proper fix would probably to still call `fetchStatusTable(..)` but only if at least one instrument exists.

**Comment by tomlebl** [comment]
Sorry, this completely slipped under my radar.
I came across this issue while ago and fixed it. On fresh install instead of 404 error modal with instructions to add instrument pops up.
